name: "Allure Report Action with Subfolders"
description: "Generate Allure Report from subfolders with history from subfolders in the allure results directory"
author: "WagnerJacqueline"
branding:
  icon: "layout"
  color: "green"
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
runs:
  using: "docker"
  image: "Dockerfile"
